(async()=>{
  const r=window.__retro, assert=(ok,message)=>{if(!ok)throw Error(message)}, frame=()=>new Promise(requestAnimationFrame);
  await r.app.openEditor();
  const root=document.querySelector('.editor'), model=r.app.editor.model;
  const reveal=e=>{for(let a=e.parentElement;a;a=a.parentElement)if(a.tagName==='DETAILS')a.open=true};
  const button=async(name,scope=root)=>{const e=[...scope.querySelectorAll('button')].find(e=>e.textContent===name);assert(e,`Missing ${name}`);reveal(e);e.click();await frame()};
  const field=async(name,value)=>{const e=[...root.querySelectorAll('[aria-label]')].find(e=>e.getAttribute('aria-label')===name);assert(e,`Missing ${name}`);reveal(e);if(e.type==='checkbox')e.checked=value;else e.value=String(value);e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));await frame()};
  const select=async(id,shift=false)=>{const e=root.querySelector(`[data-instance="${id}"]`);assert(e,`No part ${id}`);e.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',shiftKey:shift,bubbles:true}));await frame()};
  const place=async(type,x,z)=>{root.querySelector(`[data-part="${type}"]`).click();const svg=root.querySelector('svg'),p=new DOMPoint(x,z).matrixTransform(svg.getScreenCTM());svg.dispatchEvent(new PointerEvent('pointerdown',{clientX:p.x,clientY:p.y,button:0,bubbles:true}));await frame();await button('Select');return model.selection[0]};
  const connect=async(name,source,output,target,input)=>{await field('New signal name',name);await field('Signal source',source);await field('Signal output',output);await field('Signal target',target);await field('Signal input',input);await button('Connect signal')};
  await button('New');
  const control=await place('switch',-1,3), relay=await place('logic',4,2), other=await place('logic',4,-2), door=await place('door',0,0);
  await field('w',11.5);await field('label','WORKSHOP GATE');
  const checkpoint=await place('checkpoint',0,-2),cp=model.document.checkpoints.find(c=>c.instanceId===checkpoint);
  await field('New reset group name','circuit');await button('Add reset group');
  await select(control);await select(relay,true);await select(door,true);await field('Selected reset group','circuit');
  await select(checkpoint);await field(`Restore circuit at ${cp.id}`,true);
  assert(model.document.checkpoints[0].resetGroups.includes('circuit'),'Checkpoint reset selection lost');
  await connect('left-feed',control,'active',relay,'inputA');
  await connect('right-feed',control,'active',relay,'inputB');
  await connect('open-gate',relay,'active',door,'enable');
  await connect('spare-feed',relay,'active',other,'inputA');
  await connect('reset-gate',control,'activated',door,'reset');
  assert(model.document.signals.length===5,'UI connections not created');
  assert(root.querySelectorAll('[data-wire]').length===5,'Missing viewport signal paths');
  assert(root.querySelector('[data-wire="reset-gate"] path:nth-child(2)').getAttribute('stroke-dasharray')!== 'none','Pulse wire not distinguished');
  const good=JSON.stringify(model.document);
  await connect('bad-cycle',other,'active',relay,'inputA');
  assert(JSON.stringify(model.document)===good,'Invalid feedback changed the draft');
  assert(root.querySelector('[role=status]').textContent.includes('feedback loop'),'Cycle rejection not explained');
  const wire=root.querySelector('[data-wire="open-gate"]');wire.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await frame();
  assert(model.selection.includes(relay)&&model.selection.includes(door),'Wire selection did not find endpoints');
  await field('Signal name open-gate','door-power');
  const detail=root.querySelector('[data-editor-detail="signal-open-gate"]');await button('Rename signal',detail);
  assert(model.document.signals.some(s=>s.id==='door-power'),'Signal rename lost');
  await button('Undo');assert(JSON.stringify(model.document)===good,'Signal rename undo lost state');await button('Redo');
  const final=JSON.stringify(model.document);
  await field('Play start','spawn');await button('Play test');
  for(let i=0;i<300&&r.app.state!=='intro';i++)await frame();assert(r.app.state==='intro','Authored circuit did not start');
  const g=r.game;r.debug.fixedDt=0;g.audio=null;g.restart();g.update(1/60);
  const trace=document.querySelector('.signal-trace');trace.open=true;
  const code=r.input.settings.bindings.interact[0];window.dispatchEvent(new KeyboardEvent('keydown',{code,bubbles:true}));g.update(1/60);window.dispatchEvent(new KeyboardEvent('keyup',{code,bubbles:true}));
  for(let i=0;i<900&&g.state==='play';i++){r.input.override={x:Math.SQRT1_2,y:Math.SQRT1_2};g.update(1/60)}
  assert(g.state==='win'&&g.resetCount===0,'UI-authored switch/AND/door course not physically solvable');
  assert(g.checkpointSnapshot.checkpointId===cp.id,'Authored checkpoint not reached');
  // Sample the same live view used by the frame loop, even in a frozen diagnostic run.
  r.app.circuitTrace.update(r.app.session,performance.now()+1000);
  const choice=trace.querySelector('select');choice.value=door;choice.dispatchEvent(new Event('change'));
  assert(trace.textContent.includes('Latest input enable: ON via door-power'),'Trace omitted current door input');
  assert(trace.textContent.includes('left-feed')||trace.textContent.includes('right-feed'),'Trace omitted upstream cause');
  const state=g.dynamics.components.find(c=>c.id===door).capture();assert(state.amount>.99,'Door did not physically open');
  // Change the live mechanism, then die: the author-selected group restores it.
  g.physics.resetBall(g.ball,g.ballPosition.clone().set(0,.6,-2));g.ball.body.setGravityScale(1,true);g.setState('play');r.input.override={x:0,y:0};
  g.dynamics.switches[0].interact();g.update(1/60);assert(!g.dynamics.switches[0].stateOutputs().active,'Probe did not change live circuit');
  g.physics.resetBall(g.ball,g.ballPosition.clone().set(30,-30,30));
  for(let i=0;i<180;i++)g.update(1/60);
  assert(g.state==='play'&&g.resetCount===1&&g.dynamics.switches[0].stateOutputs().active,'Editor checkpoint reset group failed to restore circuit');
  const completion={time:g.runTime,initialWin:true,checkpointReset:true};
  document.querySelector('.runtime-toolbar button:last-child').click();
  for(let i=0;i<300&&r.app.state!=='editor';i++)await frame();
  assert(r.app.state==='editor'&&!r.app.session&&g.physics.disposed,'Play session not disposed');
  assert(JSON.stringify(model.document)===final,'Play mutated circuit draft');
  assert(!trace.hidden&&trace.textContent.includes('Last play test; may differ'),'Saved trace missing after disposal');
  assert(trace.textContent.includes('Latest input enable: ON via door-power'),'Saved trace lost input state');
  const saved=trace.textContent;
  await field('Course name','Workshop Circuit');assert(trace.textContent===saved,'Draft edits mutated last-play evidence');
  await button('Export');const exported=await(await fetch(r.app.editor.downloadUrl)).json();
  assert(exported.signals.some(s=>s.id==='door-power')&&exported.checkpoints[0].resetGroups.includes('circuit'),'Export lost circuit/reset contract');
  await button('Fit course');trace.open=false;
  return {completion,signals:exported.signals.length,resetGroups:exported.resetGroups,invalidCycle:'rejected atomically',trace:'current input, upstream cause and detached last play',authoring:'UI events only; model used for assertions',draftText:JSON.stringify(exported),exported};
})()
