(async () => {
  const app = window.__retro.app, renderer = app.renderer.renderer;
  const { loadLevelDocument } = await import(new URL('src/content/Catalogue.ts', location.href).href);
  const assert = (condition, message) => { if (!condition) throw new Error(message); };
  const frame = () => new Promise(requestAnimationFrame);
  const resources = () => ({ ...renderer.info.memory, programs: renderer.info.programs.length, roots: app.renderer.scene.children.length, cameraChildren: app.renderer.camera.children.length });
  const audit = [];
  let baseline;
  for (let cycle = 0; cycle < 22; cycle++) {
    const id = cycle % 2 === 0 ? 'legacy' : 'relay';
    await app.loadLevel(id);
    const session = app.session;
    session.game.boot();
    for(let i=0;i<12 && renderer.info.memory.geometries < 20;i++) await frame();
    assert(renderer.info.memory.geometries >= 20, 'Course was not rendered before teardown');
    assert(session.physics.world.bodies.len() === (id === 'legacy' ? 3 : 1), 'Duplicated physics bodies');
    const audio = session.audio.graph;
    assert(audio && audio.ctx.state === 'running', 'Audio did not start');
    const music = session.audio.music;
    assert(music.timer !== null, 'Soundtrack did not schedule');
    const oldInput = session.input;
    const loaded = resources();
    await app.returnToHub(); await frame();
    assert(app.session === null && app.state === 'hub', 'Hub retained session');
    assert(audio.ctx.state === 'closed' && music.timer === null, 'Old audio context or music scheduler survived');
    window.dispatchEvent(new KeyboardEvent('keydown', { code: 'ArrowUp' }));
    assert(!oldInput.isDown('ArrowUp'), 'Disposed input handler still receives keys');
    window.dispatchEvent(new KeyboardEvent('keyup', { code: 'ArrowUp' }));
    assert(session.game.root.children.length === 0 && session.background.group.children.length === 0, 'Owned render roots survived disposal');
    const unloaded = resources();
    assert(unloaded.roots === 1 && unloaded.cameraChildren === 0, 'Scene or camera retained session children');
    if (cycle === 1) baseline = unloaded;
    if (cycle > 1) assert(JSON.stringify(unloaded) === JSON.stringify(baseline), `Resource accumulation: ${JSON.stringify({ baseline, unloaded, cycle })}`);
    audit.push({ cycle, id, loaded, unloaded });
  }
  await Promise.all([app.loadLevel('legacy'), app.loadLevel('relay')]);
  assert(app.session.document.id === 'relay', 'Queued transition order changed');
  app.session.audio.setMuted(true); await app.loadLevel('relay');
  assert(app.session.audio.isMuted, 'Transition lost master mute'); app.session.audio.setMuted(false);
  const relay = app.session;
  relay.game.boot(); app.debug.fixedDt = 0;
  relay.input.override = { x: Math.SQRT1_2, y: Math.SQRT1_2 };
  for (let step = 0; step < 2400 && relay.game.state !== 'win'; step++) relay.game.update(1 / 120);
  assert(relay.game.state === 'win' && relay.game.resetCount === 0, 'Relay route failed');
  assert(relay.game.dynamics.checkpoints[0].active, 'Relay checkpoint did not activate');
  const snapshot = JSON.parse(JSON.stringify(relay.game.captureCheckpoint('checkpoint-1')));
  assert(snapshot.levelId === 'relay' && snapshot.groups.course && !JSON.stringify(snapshot).includes('handle'), 'Snapshot contains invalid ownership data');
  app.debug.fixedDt = null;
  for(let i=0;i<12 && app.state !== 'results';i++) await frame();
  assert(app.state === 'results', 'Results did not propagate to application');
  app.togglePause(); const time = relay.physics.simulationTime;
  for(let i=0;i<4;i++) await frame();
  assert(relay.physics.simulationTime === time && app.state === 'paused', 'Pause advanced simulation');
  app.togglePause(); assert(app.state === 'results', 'Pause failed to restore results state');
  await app.loadDocument({ schemaVersion: 999 });
  assert(app.state === 'error' && app.session === null, 'Malformed document did not fail safely');
  await app.returnToHub();
  assert(app.state === 'hub', 'Cannot recover from invalid level');
  const resetDocument = loadLevelDocument('relay');
  resetDocument.resetGroups[0].policy = 'checkpoint'; resetDocument.checkpoints[0].resetGroups = ['course'];
  await app.loadDocument(resetDocument);
  const resetGame = app.session.game; resetGame.boot(); app.debug.fixedDt = 0;
  const checkpoint = resetGame.dynamics.checkpoints[0];
  resetGame.physics.resetBall(resetGame.ball, checkpoint.spawn); resetGame.update(1/120);
  assert(checkpoint.active, 'Checkpoint fixture did not activate');
  checkpoint.active = false;
  resetGame.die('fall');
  for(let i=0;i<180 && resetGame.state === 'reset';i++) resetGame.update(1/120);
  assert(checkpoint.active && resetGame.state === 'play', 'Checkpoint group did not restore captured logical state');
  const doc = loadLevelDocument('relay'); doc.metadata.name = '<img src=x onerror=alert(1)>';
  await app.loadDocument(doc);
  assert(!document.querySelector('#overlay img'), 'Course title was interpreted as executable markup');
  await app.returnToHub();
  return { cycles: 20, warmupCycles: 2, relay: 'WIN without resets', malformedRecovery: 'passed', queuedTransitions: 'passed', pause: 'passed', snapshots: 'serialisable and reset groups restored', audit };
})()
